### PR TITLE
Changes to build sfc_climo_gen on Hera

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
This commit adds a Hera module file for the sfc_climo_gen utility and a Hera stanza in the machine-setup.sh file to compile on Hera.

### CODE REVIEW

**Comment by llpcarson** [comment]
Jeff - could you add a short description of the change, for the record?  Just a sentence, thanks!

**Comment by JeffBeck-NOAA** [comment]
> Jeff - could you add a short description of the change, for the record? Just a sentence, thanks!

Sure!  This commit adds a Hera module file for the sfc_climo_gen utility and a Hera stanza in the machine-setup.sh file to compile on Hera.

**Comment by llpcarson** [comment]
THanks - I pasted it into the PR "description section".

**Review by llpcarson — APPROVED** [review]
Approved

**Pull request merged**
