### PR TITLE
Added Hera stanza to machine-setup.sh and an addition Hera module fil…

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
…e to build chgres_cube on Hera.  Also removed duplicate submodules in a couple chgres_cube fortran files following input from Larissa

### CODE REVIEW

**Comment by llpcarson** [comment]
Just confirming - feature/chgres_grib2 is the correct target for this change?  Not dtc/develop?  Is there a plan to get this into a combined branch at some point?  If Larissa is maintaining it (?), then perhaps not for now...

**Review by llpcarson — APPROVED** [review]
Approved, please confirm the target branch before merging!

**Comment by JeffBeck-NOAA** [comment]
Thank you, Laurie!  Yes, there are two branches in UFS_UTILS that need to
be updated for Hera: dtc/develop and feature/chgres_grib2.  With this
commit, UFS_UTILS should work in the community workflow on Hera.

**Comment by JeffBeck-NOAA** [comment]
> Just confirming - feature/chgres_grib2 is the correct target for this change? Not dtc/develop? Is there a plan to get this into a combined branch at some point? If Larissa is maintaining it (?), then perhaps not for now...

Yes, there is a plan to merge Larissa's grib2 changes for chgres_cube into the develop branch in UFS_UTILS.  However, George is still testing her changes, and there is no ETA on when this merge will occur.

**Pull request merged**
