### PR TITLE
feature/chgres_grib2: portability changes for GNU compiler, build environment for macOS

### PR DESCRIPTION
**Pull request by climbfuji**
This PR adds portability changes for compiling and running with the GNU compiler on macOS platforms. The majority of changes deals with fixing incorrect (lowercase) preprocessor macros:
```
-if(ESMF_logFoundError(rcToCheck=ierr,msg=ESMF_LOGERR_PASSTHRU,line=__line__,file=__file__)) &
+if(ESMF_logFoundError(rcToCheck=ierr,msg=ESMF_LOGERR_PASSTHRU,line=__LINE__,file=__FILE__)) &
```
Other changes for GNU are the correct declaration of character arrays of variable length and support for building on macOS platforms.

### CODE REVIEW

**Comment by climbfuji** [comment]
Attached are three images of selected fields in the resulting initial surface conditions: islmsk, t2m, stc layer 5 - the min/max range is identical (to six significant digits in ncview) between the macOS/GNU file (`out.sfc.tile7.nc`) and the Hera/Intel (`sfc_data.tile7.nc`)

Screen Shot 2019-09-26 at 4 03 33 PM
Screen Shot 2019-09-26 at 4 03 07 PM
Screen Shot 2019-09-26 at 4 02 39 PM

**Comment by climbfuji** [comment]
One more image from `out.atm.tile7.nc` versus `gfs_data.tile7.nc` (sphum, level 44/64) - min/max range for sphum is also identical (to six significant digits in ncview) for both macOS/GNU and Hera/Intel.

Screen Shot 2019-09-26 at 4 07 53 PM

**Comment by climbfuji** [comment]
Note: I had to remove the hardcoded `FCCOMP` and `FFLAGS` settings in `sorc/chgres_cube.fd/makefile` and re-enable those in `modulefiles/chgres_cube.*`

**Comment by JulieSchramm** [comment]
@climbfuji Did you run this on hera with your mods to get the plots?

**Comment by climbfuji** [comment]
No. The plots were generated from my runs on the mac and compared to output data I received from @JeffBeck-NOAA (who ran the unmodified version on hera/intel). The easiest would be if someone with an existing setup on hera could run the current chgres_grib2 branch and my branch and compare the two (not sure if I have time for this today, and I don't have a working setup on hera yet).

**Comment by JulieSchramm** [comment]
@climbfuji @JeffBeck-NOAA I will test this PR when my setup on hera can generate BFB results with the current chgres_grib2 branch, hopefully Monday.

**Comment by climbfuji** [comment]
Thanks very much, Julie!

**Comment by JulieSchramm** [comment]
climbfuji:portability_gnu_macosx branch runs on hera with the regional_workflow. gfs_data.tile7.nc is BFB with NCAR:feature/chgres_grib2.  sfc_data.tile7.nc differs in the sheleg variable, as expected:
DIFFER : VARIABLE : sheleg : POSITION : [0,66,0] : VALUES : -0.0212927 <> 253.264

**Comment by climbfuji** [comment]
> climbfuji:portability_gnu_macosx branch runs on hera with the regional_workflow. gfs_data.tile7.nc is BFB with NCAR:feature/chgres_grib2. sfc_data.tile7.nc differs in the sheleg variable, as expected:
> DIFFER : VARIABLE : sheleg : POSITION : [0,66,0] : VALUES : -0.0212927 <> 253.264

Great, thanks for testing and merging. Why is the difference in sheleg expected? Sorry if this is a dumb question.

**Comment by JulieSchramm** [comment]
I have seen this difference since about mid-September.  Looking at the
sheleg and snwdph fields in the sfc_data.tile7.nc, there are bands of snow
on both sides of Florida.  I can't get BFB results for these two fields
when I run the out-of-the-box case twice.  This is bothersome to me, but
I'm not sure if anyone knows what the problem is.

**Comment by climbfuji** [comment]
Thanks for the info. Yeah, bothersome.

**Comment by JeffBeck-NOAA** [comment]
Hi Julie,

The problem with strange patterns in sheleg and snwdph should be fixed
now.  Did you try starting from scratch and re-cloning everything?

- Jeff

**Comment by JulieSchramm** [comment]
Yes, first I tried with all of my forks and branches up to date, but the
snow fields were still different.  So I re-cloned everything in a new
directory and am still getting differing sfc_data.tile7.nc files.  I am
using code from the top of each repository.  I keep looking at the
chgres_cube code, but the problem could be in the workflow.

**Comment by JeffBeck-NOAA** [comment]
OK, when you recloned everything in a new directory, did the sheleg and
snwdph variables look good?

- Jeff

**Comment by JulieSchramm** [comment]
No, after re-cloning, there are still the horizontal lines in the snow
fields.

**Pull request merged**
